# Generated by Django 3.0.3 on 2020-02-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='events',
            field=models.ManyToManyField(to='events.Event'),
        ),
    ]
