# Generated by Django 3.0.3 on 2020-02-18 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_registration_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='events',
        ),
        migrations.AddField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(default=9999, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
            preserve_default=False,
        ),
    ]
