# Generated by Django 3.0.3 on 2020-02-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200218_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='last_name',
            field=models.CharField(default=9999, max_length=50),
            preserve_default=False,
        ),
    ]
