# Generated by Django 3.0.3 on 2020-02-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_registration_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='mail_id',
            new_name='email',
        ),
    ]
