# Generated by Django 3.0.3 on 2020-02-18 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200218_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='last_name',
        ),
    ]
