# Generated by Django 3.0.3 on 2020-02-19 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_registration_last_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('event', 'email')},
        ),
    ]
