# Generated by Django 3.0.3 on 2020-02-23 05:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20200219_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.CharField(blank=True, default='System', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_by',
            field=models.CharField(blank=True, default='System', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='created_by',
            field=models.CharField(blank=True, default='System', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='updated_by',
            field=models.CharField(blank=True, default='System', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(limit_choices_to={'start_time__gte': datetime.datetime(2020, 2, 23, 5, 17, 53, 307269, tzinfo=utc)}, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
