# Generated by Django 3.0.3 on 2020-02-23 08:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20200223_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(limit_choices_to={'start_time__gte': datetime.datetime(2020, 2, 23, 8, 30, 13, 736008, tzinfo=utc)}, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
