# Generated by Django 3.0.3 on 2020-02-24 10:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20200223_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(limit_choices_to={'start_time__gte': datetime.datetime(2020, 2, 24, 10, 56, 15, 178913, tzinfo=utc)}, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
