# Generated by Django 3.0.3 on 2020-02-24 12:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20200224_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(limit_choices_to={'start_time__gte': datetime.datetime(2020, 2, 24, 12, 40, 41, 909112, tzinfo=utc)}, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
